services:
  blockheads:
    image: ghcr.io/wingysam/blockheads-docker
    container_name: blockheads
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ./saves:/saves
    ports:
      - "15151:15151/udp"
    command: ["--new", "MY WORLD", "--no-exit"]
